/**
 * Load / dump demo state. Seed files live in apps/server/seed/.
 *   fresh.json              — start of the demo (Thabo's need is typed in live)
 *   eight-weeks-later.json  — generated by `pnpm seed:build`; demo programme delivered
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { count } from "drizzle-orm";
import type { DemoState } from "shared";
import { db, schema } from "./client";

export const SEED_DIR = join(dirname(fileURLToPath(import.meta.url)), "../../seed");

const INSERT_ORDER = [
  ["schools", schema.schools],
  ["fields", schema.fields],
  ["coaches", schema.coaches],
  ["equipment_kits", schema.equipment_kits],
  ["transport_offers", schema.transport_offers],
  ["sponsor_budgets", schema.sponsor_budgets],
  ["community_needs", schema.community_needs],
  ["opportunity_bundles", schema.opportunity_bundles],
  ["assignments", schema.assignments],
  ["delivery_evidence", schema.delivery_evidence],
  ["audit_events", schema.audit_events],
] as const;

export type SeedKey = (typeof INSERT_ORDER)[number][0];
export type SeedFile = { _note?: string } & Partial<Record<SeedKey, Record<string, unknown>[]>>;

export function readSeedFile(state: DemoState): SeedFile {
  const file = state === "fresh" ? "fresh.json" : "eight-weeks-later.json";
  return JSON.parse(readFileSync(join(SEED_DIR, file), "utf8")) as SeedFile;
}

/** Wipe every table and load a seed, in one transaction (takes a few ms). */
export function loadSeedData(data: SeedFile) {
  db.transaction((tx) => {
    for (const table of schema.TABLES_CHILD_FIRST) tx.delete(table).run();
    for (const [key, table] of INSERT_ORDER) {
      const rows = data[key] ?? [];
      // Rows come from our own JSON files; Drizzle validates column names at insert.
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      for (const row of rows) tx.insert(table).values(row as any).run();
    }
  });
}

export function loadSeed(state: DemoState) {
  loadSeedData(readSeedFile(state));
}

export function isEmpty() {
  const row = db.select({ n: count() }).from(schema.schools).get();
  return !row || row.n === 0;
}

/** Every table as plain JSON — used by scripts/build-seed.ts. */
export function dumpDb(): SeedFile {
  const out: SeedFile = {};
  for (const [key, table] of INSERT_ORDER) out[key] = db.select().from(table).all() as Record<string, unknown>[];
  return out;
}
