/**
 * Generates seed/eight-weeks-later.json by playing the demo through the REAL
 * services (engine + status machine), so the "8 weeks later" state is always
 * consistent with what the live demo would produce.
 *
 *   pnpm seed:build
 *
 * Re-run whenever fresh.json, the engine or the scoring weights change.
 */
export {};

// Env must be set before the DB/config modules load, hence the dynamic imports below.
process.env.DB_PATH = ":memory:";
process.env.TRACE_PACE_MS = "0";

const { writeFileSync } = await import("node:fs");
const { join } = await import("node:path");
const { loadSeed, dumpDb, SEED_DIR } = await import("../src/db/seed");
const { createNeed, solveNeed, approveBundle, addEvidence } = await import("../src/services/needs");
const { computeImpact } = await import("../src/lib/impact");

loadSeed("fresh");

// 1. The scripted demo need, exactly as the coach confirms it on stage.
const need = createNeed({
  school_id: "school-thabo",
  age_group: "U16",
  gender: "girls",
  participants: 28,
  days: ["tue"],
  start_time: "15:00",
  end_time: "17:00",
  needs: { field: true, coach: true, balls: 6, transport: false },
  weeks: 8,
  raw_input: "We've got 28 under-16 girls who can train on Tuesdays after school. We need a field, a coach and six balls.",
});

// 2. Solve + approve the top bundle, starting 8 weeks before the "now" of this seed.
const { response } = solveNeed(need.id, { paceMs: 0 });
if (!response.feasible) throw new Error("Demo need should be feasible — check fresh.json / engine");
const start = new Date("2026-08-04"); // a Tuesday
const { assignment } = approveBundle(response.bundles[0].id, {
  owner_role: "coordinator",
  start_date: start.toISOString().slice(0, 10),
});

// 3. Eight weekly sessions with realistic attendance for a squad of 28.
const attendance = [24, 26, 27, 25, 28, 26, 27, 28];
attendance.forEach((count, week) => {
  const d = new Date(start);
  d.setDate(d.getDate() + week * 7);
  addEvidence(assignment.id, { session_date: d.toISOString().slice(0, 10), attendance_count: count });
});

// 4. Ridgeview gets solved so the dashboard shows its unmet, sponsor-ready request.
solveNeed("need-3", { paceMs: 0 });

const out = {
  _note: "SYNTHETIC hackathon data: 8 weeks after the demo programme was approved. GENERATED by `pnpm seed:build` — do not hand-edit.",
  ...dumpDb(),
};
writeFileSync(join(SEED_DIR, "eight-weeks-later.json"), JSON.stringify(out, null, 2) + "\n");

const impact = computeImpact();
console.log(
  `eight-weeks-later.json written: ${impact.participant_sessions} participant-sessions, ` +
    `${impact.programmes_delivered} delivered, ${impact.unmet_requests.length} unmet request(s)`,
);
